---
all:
  children:
    nds_servers:
      hosts:
        nds2:
          ansible_host: 5.75.190.44
          server_name: "[EU] Bizarre Adventure #1"
          game_port: 7777
          server_id: alpha
          maps:
            - "Luna"
            - "Singularity"
            - "Broken Heart L"
            - "Gold Rush"
            - "Bloodmoon Remastered"
            - "Red River"
            - "Broken Spirit L"
            - "Broken Trust Ring"
            - "Heartstones"
            - "Colosseum"
            - "Honeycomb"
            - "Aorta"
            - "Gold Rush"
            - "Salar"
            - "Yukon"
            - "Arroyo"
          mods:
            - "2772151779"
            - "2958486072"
            - "2925150813"
            - "2837657528"
            - "2838751908"
            - "3092214727"
            - "3171410777"
            - "2873648985"
            - "3092254040"
            - "3092257928"
            - "3103075720"
            - "3343210737"
            - "3297165737"
            - "2865123929"
            - "2925472192"
            - "3292576588"
            - "2875764771"
        nds3:
          ansible_host: 37.27.181.203
          server_name: "[EU] Bizarre Adventure #2"
          game_port: 7777
          server_id: bravo
          maps:
            - "Artefact"
            - "Breach"
            - "Doorknob"
            - "Doorknob - Small"
            - "Phage"
            - "Styx"
            - "Giant Coral"
            - "Ralas"
            - "Shattered Giant"
            - "Honeycomb"
            - "Aorta"
            - "Gold Rush"
            - "Salar"
            - "Yukon"
            - "Arroyo"
          mods:
            - "3342645384"
            - "3382553291"
            - "3380327922"
            - "3365340376"
            - "2867569799"
            - "2798446763"
            - "3261294063"
            - "3292576588"
            - "2865123929"
            - "2925472192"
            - "2837657528"
            - "2925150813"
            - "2875764771"
      vars:
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    
    abiotic_servers:
      hosts:
        nds3:
      vars:
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
